repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 2a7c5cc44508119d0935b71797f61725c41af307 # uv 0.8.3
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 6c5418a077bd954e7078087a655421b85772095b # v0.12.4
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: local
    hooks:
      - id: tests
        name: run unit tests
        language: system
        entry: uv run pytest
        pass_filenames: false
